<?php
$data = array (
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'Clothing',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => 'Clothing',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'Swimwear',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => 'Swimwear',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'Vest',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '63',
    'name' => 'Vest',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'T-shirts',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => 'T-shirts',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Skirts',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => 'Skirts',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => 'Shorts',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '64',
    'name' => 'Shorts',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Dresses',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => 'Dresses',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => 'Blouses',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '61',
    'name' => 'Blouses',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'Men\'s cloth',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => 'Men\'s cloth',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => 'Jacket',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => 'Jacket',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Accessories',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => 'Accessories',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => 'Wigs',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => 'Wigs',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => 'Scarves',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => 'Scarves',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => 'Wallets',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => 'Wallets',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'Hats',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => 'Hats',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => 'Gloves',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => 'Gloves',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => 'Belts',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => 'Belts',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => 'Handbags',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => 'Handbags',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'Shoes',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => 'Shoes',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => 'Flats',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => 'Flats',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'Wedges',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => 'Wedges',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'Pumps',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => 'Pumps',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'Sneakers',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => 'Sneakers',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => 'Boots',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => 'Boots',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'Sandals',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => 'Sandals',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'Jewelry',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => 'Jewelry',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'Brooches',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '53',
    'name' => 'Brooches',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => 'Earrings',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '50',
    'name' => 'Earrings',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => 'Necklaces',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
    'level' => 1,
    'id' => '18',
    'name' => 'Necklaces',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'Bracelets',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '51',
    'name' => 'Bracelets',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'Rings',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '52',
    'name' => 'Rings',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => 'Beauty',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '54',
    'name' => 'Beauty',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'Health tool',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '57',
    'level' => 1,
    'id' => '58',
    'name' => 'Health tool',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'other',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '66',
    'name' => 'other',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'Beauty tools',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => 'Beauty tools',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'Children',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => 'Children',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'Puzzle Toys',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => 'Puzzle Toys',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Stationery',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => 'Stationery',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'other',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '65',
    'name' => 'other',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => 'Kids Clothing',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => 'Kids Clothing',
  ),
);
?>